site_name: CIMPL Project
nav:
       - About: 
              - about.md
              - cimplReleaseNotes.md
       - Installation:
              - cimplInstall.md              
       - Tutorials:
              - cimpl6Tutorial_helloWorld.md
              - cimpl6Tutorial_detail.md
       - User Guides:
              - cimpl6Authoring.md
              - cimpl6ObjectiveFHIR.md
       - Reference Manuals: 
              - cimpl6LanguageReference.md
              - cimpl6ToolingReference.md
       
theme: 
       name: mkdocs
       custom_dir: custom_theme/
       static_templates:
              - footer.html
       extra_css:
              - css/extra.css
              - css/theme_extra.css
       markdown_extensions:
       - smarty
       - toc:
              permalink: "#"
              baselevel: 1
              toc_depth: 1
       - sane_lists
       - admonition